name: locator_mobile
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  
  flutter_map: ^6.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  http: ^1.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  latlng: ^2.0.7
  meta: ^1.9.1
  

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.2
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: SplineSans
      fonts:
        - asset: fonts/static/SplineSans-Regular.ttf
  assets:
    - assets/.env